DROP SEQUENCE MYMEMBERSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MYMEMBERSEQ;
--멤버번호, 아이디, 패스워드, 이름, 주소, 전화번호, 이메일, 가입여부, 등급
--가입여부(Y/N), 등급(admin, user, ...)
CREATE TABLE MYMEMBER(
	MYNO NUMBER NOT NULL,					--PK
	MYID VARCHAR2(500) NOT NULL,		--UNIQUE
	MYPW VARCHAR2(500) NOT NULL,
	MYNAME VARCHAR2(500) NOT NULL,
	MYADDR VARCHAR2(4000) NOT NULL,
	MYPHONE VARCHAR2(20) NOT NULL,	--UNIQUE
	MYEMAIL VARCHAR2(100) NOT NULL,	--UNIQUE
	MYENABLED VARCHAR2(2) NOT NULL,
	MYROLE VARCHAR2(100) NOT NULL,
	
	CONSTRAINT PK_MYNO PRIMARY KEY (MYNO),
	CONSTRAINT UN_MYID UNIQUE (MYID),
	CONSTRAINT UN_MYPHONE UNIQUE (MYPHONE),
	CONSTRAINT UN_MYEMAIL UNIQUE (MYEMAIL),
	CONSTRAINT CHK_ENABLED CHECK (MYENABLED IN ('Y','N'))
);

SELECT * FROM MYMEMBER;