/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.49
 * Generated at: 2020-01-11 09:34:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');

	response.setContentType("text/html; charset=UTF-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tdocument.getElementById(\"SUBMIT\").disabled = \"disabled\";\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"input[name='MYID']\").blur(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar id = $(\"input[name='MYID']\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\tif(id.val() == null || id.val() == \"\"){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력해 주세요!\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\turl : \"logincontroller.jsp?command=ajaxIdChk\",\r\n");
      out.write("\t\t\t\t\tdata : { MYID : $(\"input[name='MYID']\").val() },\r\n");
      out.write("\t\t\t\t\tdatatype : \"JSON\",\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuccess:function(args){\r\n");
      out.write("\t\t\t\t\t\tvar res = JSON.parse(args).idnotused;\r\n");
      out.write("\t\t\t\t\t\t//alert(res);\r\n");
      out.write(" \t\t\t\t\t\tif(res){\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementsByName(\"MYID\")[0].title='y';\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementsByName(\"MYPW\")[0].focus();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"idtext\").innerHTML = \"아이디(사용가능)\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"idtext\").style.color=\"blue\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"SUBMIT\").disabled = \"\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementsByName(\"MYID\")[0].title='n';\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementsByName(\"MYID\")[0].focus();\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"idtext\").innerHTML = \"아이디(사용불가)\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"idtext\").style.color=\"red\";\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\terror:function(request, status, error){\t\r\n");
      out.write("\t\t\t\t\t\t// 통신 실패하면 실행\r\n");
      out.write("\t\t\t\t\t\talert(\"실패!\")\r\n");
      out.write("\t\t\t\t\t\talert(\"code : \" + request.status + \"\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\t\t\"message : \" + request.responseText + \"\\n\" + \r\n");
      out.write("\t\t\t\t\t\t\t\t\"error : \" + error);\r\n");
      out.write("\t\t\t\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction idChkConfirm(){\r\n");
      out.write("\t\tvar chk = document.getElementsByName(\"MYID\")[0].title;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(chk == \"n\"){\r\n");
      out.write("\t\t\tdocument.getElementById(\"idtext\").innerHTML = \"아이디(필수정보입니다.)\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"idtext\").style.color=\"red\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t//document.getElementsByName(\"MYID\")[0].focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>회원가입</h1>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"logincontroller.jsp\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"registres\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th id=\"idtext\">아이디</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"MYID\" title=\"n\" required=\"required\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>비밀번호</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"MYPW\" required=\"required\" onclick=\"idChkConfirm();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이름 :</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"MYNAME\" required=\"required\" onclick=\"idChkConfirm();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>주소 :</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"MYADDR\" required=\"required\" onclick=\"idChkConfirm();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>전화번호 :</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"MYPHONE\" required=\"required\" onclick=\"idChkConfirm();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>이메일 :</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"MYEMAIL\" required=\"required\" onclick=\"idChkConfirm();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"회원가입\" id=\"SUBMIT\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- <tr>\r\n");
      out.write("\t\t\t\t<th>등급 :</th>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select name=\"MYROLE\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"USER\">일반회원</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"MANAGER\">우수회원</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"ADMIN\">관리자</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
